### ISSUE TITLE
NullReference Exception

### ISSUE THREAD

**Issue by Bian-Sh** [SolidAlloy/ExtEvents#1]
Unity Version : Unity 2020.2.1f1
ExtEvents Version: 1.0.3
Exception below 👇
![image](https://user-images.githubusercontent.com/24520547/153707878-a00ff236-178a-4803-b847-ab935d5c52ad.png)

It seems that there is no such api  that named "scheduleRemove" in the type named "UnityEditorInternal.ReorderableList"

**Comment by SolidAlloy** [comment]
Hi, thanks for submitting the issue. It's been fixed in the [1.1.0](https://github.com/SolidAlloy/ExtEvents/releases/tag/1.1.0) version of the plugin.
