### ISSUE TITLE
[Solved] Vscode cannot see the assembly reference, intellisense isnt working properly.

### ISSUE THREAD

**Issue by TheBricktop** [SolidAlloy/ExtEvents#4]
[SOLUTION] : [This solution works well](https://stackoverflow.com/questions/60124065/unity-omnisharp-is-not-finding-referenced-projects-in-vscode) Basically You have to recreate allthe csproj in the external code editor settings in preferences.
Even though the code is interpreted correctly the vscode editor is not recognizing the assembly reference correctly :

![obraz](https://user-images.githubusercontent.com/3866030/155125686-4dec5949-66c5-43a4-88de-6f62d6ca2dca.png)

**Comment by SolidAlloy** [comment]
Thanks for posting the solution! I haven't worked with VS Code. Hopefully, the bug doesn't reappear in new versions.
