### ISSUE TITLE
Nested list ExtEvent argument is not visualized properly in the inspector

### ISSUE THREAD

**Issue by Ivan-Vankov** [SolidAlloy/ExtEvents#5]
Take the following code:
``` csharp
public class TestExtEvent : MonoBehaviour {
    [Serializable]
    public struct TestStruct {
        public List<string> stringList;
    }
    [EventArguments("Test Struct", "Int Val")]
    public ExtEvent<TestStruct, int> testStructIntExtEvent;
    public void TestStructIntMethod(TestStruct testStruct, int intVal) { }
}
```
When the TestStructIntMethod is assigned to the testStructIntExtEvent it looks like this in the inspector:
![image](https://user-images.githubusercontent.com/28845261/167181560-2d89aa93-a3ae-4088-a5bb-1e929187801a.png)
However when Test Struct is expanded it looks like this:
![image](https://user-images.githubusercontent.com/28845261/167181799-1db7c52c-7751-4aa6-9262-bd5df0d06285.png)
The stringList member of the test struct is drawn twice in a self-overlapping manner.
It also obstructs the following second int paramenter of testStructIntExtEvent.

This is **NOT** the case when the list is not nested:
![image](https://user-images.githubusercontent.com/28845261/167182860-20c5fa23-a4b6-4920-92bf-339cf77a2944.png)

**Comment by SolidAlloy** [comment]
Hi, thanks for reporting the issue! It's been fixed, please check it out in [1.2.2](https://github.com/SolidAlloy/ExtEvents/releases/tag/1.2.2)
